/*
 * generated by Xtext 2.31.0
 */
package org.xtext.example.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import xtext.tutorial.ui.internal.TutorialActivator;

public class TutorialUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TutorialActivator.getInstance().getInjector("org.xtext.example.Tutorial");
	}

}
